name: branch based
on: 
    # push:
    workflow_dispatch:
jobs:
    job_1:
        if: contains(github.ref,'main' )
        runs-on: ubuntu-latest
        environment: production
        steps:
            - name: deploy
              run: echo "${{vars.environment_txt}}"
    job2:
        if: contains(github.ref,'dev' ) 
        runs-on: ubuntu-latest
        environment: staging
        steps:
            - name: deploy
              run: echo "${{vars.environment_txt}}"
           