name: env feature
on: 
    workflow_dispatch:
        inputs:
            environment:
                description: choose deploying environment
                type: choice
                required: true
                options: ['staging' , 'production']
jobs:
    job_1:
        runs-on: ubuntu-latest
        # environment: ${{ github.event.inputs.environment }}
        steps:
            - name: deploy
              run: echo "${{vars.environment_txt}}"