name: matrix-ci
on:
    push:
    workflow_dispatch:
jobs:
    job1:
        runs-on: ${{matrix.os}}
        strategy:
            matrix:
                os: [ubuntu-latest,windows-latest]
                ver: [16,18,20]
                exclude:
                    - os: windows-latest
                      ver: 16
                include:
                    - os: ubuntu-latest
                      ver: 21
            fail-fast: true
            max-parallel: 2
        steps:
            - name: check version
              uses: actions/setup-node@v6
              with:
                node-version: ${{matrix.ver}}
            - name: echo
              run: "echo runuing on ${{matrix.os}} and node version ${{matrix.ver}}"